spring.application.name=enterprise-order-system

spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_order
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true